### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by wschella** [ZeusWPI/zeus.ugent.be#273]
Building gives me this error:

```
Captain! We’ve been hit!

  ... 8 lines omitted (see crash.log for details)
  9. from /var/lib/gems/2.5.0/gems/nanoc-4.9.2/lib/nanoc/base/entities/action_sequence.rb:50:in `each'
  8. from /var/lib/gems/2.5.0/gems/nanoc-4.9.2/lib/nanoc/base/entities/action_sequence.rb:50:in `each'
  7. from /var/lib/gems/2.5.0/gems/nanoc-4.9.2/lib/nanoc/base/entities/action_sequence.rb:50:in `block in each'
  6. from /var/lib/gems/2.5.0/gems/nanoc-4.9.2/lib/nanoc/base/services/compiler/phases/recalculate.rb:30:in `block in run'
  5. from /var/lib/gems/2.5.0/gems/nanoc-4.9.2/lib/nanoc/base/services/executor.rb:22:in `filter'
  4. from /var/lib/gems/2.5.0/gems/nanoc-4.9.2/lib/nanoc/base/services/filter.rb:157:in `setup_and_run'
  3. from /var/lib/gems/2.5.0/gems/nanoc-4.9.2/lib/nanoc/filters/erb.rb:36:in `run'
  2. from /usr/lib/ruby/2.5.0/erb.rb:876:in `result'
  1. from /usr/lib/ruby/2.5.0/erb.rb:876:in `eval'
  item /blog/17-18/tech-talkz.md (rep default):3:in `get_binding'

NoMethodError: undefined method `path' for nil:NilClass

```

I assume it's this line: in /blog/17-18/tech-talkz.md: `# [Talk I: Nanopixel](<%= @items['/events/17-18/nanopixel.md'].path %>)`

**Comment by wschella** [comment]
@werthen you have any idea why this happens?

**Comment by wschella** [comment]
To quote werthen:

> voer uit atm met `-e prod` (edited)
> tis omda er oude events nie worden aangemaakt in dev environment
> om de buildtijd te verkleinen
> maar ja, da referencet dus een item die niet bestaat omda we die er uit weg filteren in nanoc
